import { NextResponse } from 'next/server'

// TODO: Replace with real queries joining:
//   workflow.applications a
//   JOIN iam.organizations o          ON o.id = a.applicant_org_id
//   JOIN iam.users cu                 ON cu.id = a.submitted_by
//   JOIN device.type_approval_applications ta ON ta.application_id = a.id
//   JOIN device.device_catalog dc     ON dc.id = ta.device_model_id
//   LEFT JOIN workflow.application_tasks t ON t.application_id = a.id AND t.task_type_code = 'REVIEW'
//   LEFT JOIN iam.users ou            ON ou.id = t.assigned_to_user_id
//   LEFT JOIN workflow.application_documents d ON d.application_id = a.id

const MOCK_APPLICATIONS: Record<string, object> = {
  'TA-APP-2026-0041': {
    id: 'TA-APP-2026-0041',
    application_number: 'TA-APP-2026-0041',
    submitted_at: '2026-03-22T08:30:00Z',
    current_status_code: 'UNDER_REVIEW',
    current_stage_code: 'TECHNICAL_VALIDATION',
    priority_code: 'HIGH',
    expected_decision_at: '2026-04-05T00:00:00Z',
    applicant: {
      org_name: 'TeleCo BW (Pty) Ltd',
      contact_name: 'Kabo Moeti',
      contact_email: 'kabo.moeti@teleco.co.bw',
      contact_phone: '+267 71 234 567',
      physical_address: 'Plot 54368, Gaborone CBD, Gaborone',
      accreditation_type: 'Customer',
      accreditation_ref: 'ACC-2025-CUS-00183',
    },
    device: {
      brand_name: 'Samsung',
      marketing_name: 'Galaxy A55 5G',
      model_name: 'SM-A556B',
      is_sim_enabled: true,
      sample_imei: '352099001761481',
      country_of_manufacture: 'Vietnam',
      frequency_bands: 'B1, B3, B7, B8, B20, B28, n1, n3, n7, n28, n77, n78',
      transmission_power: '23 dBm (LTE) / 26 dBm (NR)',
      network_technology: ['LTE', '5G NR', 'WCDMA', 'GSM'],
      dimensions: '161.1 × 77.4 × 8.2 mm',
      weight: '213 g',
      battery_capacity: '5000 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 301 511', 'ETSI EN 301 908', 'ETSI EN 303 413', 'IEC 62209-1'],
      test_laboratory: 'SGS Botswana Testing Laboratory',
      test_report_ref: 'SGS-BW-2026-RF-00412',
      test_date: '2026-02-14',
      declaration: 'I hereby declare that the equipment described above complies with the relevant BOCRA type approval requirements and that the information provided is accurate and complete to the best of my knowledge.',
      previously_approved: true,
      previous_country: 'South Africa',
      previous_reference: 'ICASA-TA-2025-0031',
    },
    documents: [
      { id: 'doc-001', type_code: 'TEST_REPORT',         label: 'RF Test Report',                    status: 'VERIFIED',   file_name: 'SGS_RF_Report_SM-A556B.pdf' },
      { id: 'doc-002', type_code: 'SAR_REPORT',          label: 'SAR / EMF Report',                  status: 'VERIFIED',   file_name: 'SGS_SAR_SM-A556B.pdf' },
      { id: 'doc-003', type_code: 'SAFETY_CERT',         label: 'Electrical Safety Certificate',     status: 'VERIFIED',   file_name: 'IEC62368_Certificate.pdf' },
      { id: 'doc-004', type_code: 'USER_MANUAL',         label: 'User Manual (English)',             status: 'VERIFIED',   file_name: 'Samsung_A55_UserManual_EN.pdf' },
      { id: 'doc-005', type_code: 'LABEL_ARTWORK',       label: 'Device Label / Artwork',            status: 'SUBMITTED',  file_name: 'SM-A556B_Label.pdf' },
      { id: 'doc-006', type_code: 'BLOCK_DIAGRAM',       label: 'Block / Circuit Diagram',           status: 'SUBMITTED',  file_name: 'SM-A556B_BlockDiagram.pdf' },
      { id: 'doc-007', type_code: 'IMPORT_PERMIT',       label: 'Import Permit / Proforma Invoice',  status: 'SUBMITTED',  file_name: 'Import_Proforma_Invoice.pdf' },
      { id: 'doc-008', type_code: 'DEVICE_PHOTOS',       label: 'Device Photographs (min. 3)',       status: 'VERIFIED',   file_name: 'SM-A556B_Photos.zip' },
    ],
    assigned_to: { id: 'off-001', name: 'Lesedi Modise' },
    timeline: [
      { date: '2026-03-22T08:30:00Z', event: 'Application Submitted',           actor: 'Kabo Moeti (TeleCo BW)',     note: 'All required documents attached.' },
      { date: '2026-03-22T14:00:00Z', event: 'Initial Review Started',          actor: 'System',                    note: 'Application entered Initial Review queue.' },
      { date: '2026-03-23T09:15:00Z', event: 'Assigned to Officer',             actor: 'Admin Portal',              note: 'Assigned to Lesedi Modise for review.' },
      { date: '2026-03-24T11:30:00Z', event: 'Documents Verified',              actor: 'Lesedi Modise (Officer)',   note: 'All submitted documents reviewed and verified.' },
      { date: '2026-03-25T09:00:00Z', event: 'Advanced to Technical Validation', actor: 'Lesedi Modise (Officer)', note: 'Proceeding to technical specification review.' },
    ],
  },

  'TA-APP-2026-0038': {
    id: 'TA-APP-2026-0038',
    application_number: 'TA-APP-2026-0038',
    submitted_at: '2026-03-14T10:00:00Z',
    current_status_code: 'APPROVED',
    current_stage_code: 'COMPLETED',
    priority_code: 'NORMAL',
    expected_decision_at: '2026-03-28T00:00:00Z',
    applicant: {
      org_name: 'TeleCo BW (Pty) Ltd',
      contact_name: 'Kabo Moeti',
      contact_email: 'kabo.moeti@teleco.co.bw',
      contact_phone: '+267 71 234 567',
      physical_address: 'Plot 54368, Gaborone CBD, Gaborone',
      accreditation_type: 'Customer',
      accreditation_ref: 'ACC-2025-CUS-00183',
    },
    device: {
      brand_name: 'Xiaomi',
      marketing_name: 'Redmi Note 13',
      model_name: '23090RA98G',
      is_sim_enabled: true,
      sample_imei: '864475060012345',
      country_of_manufacture: 'China',
      frequency_bands: 'B1, B3, B7, B8, B20, B28',
      transmission_power: '23 dBm (LTE)',
      network_technology: ['LTE', 'WCDMA', 'GSM'],
      dimensions: '161.1 × 75.0 × 7.6 mm',
      weight: '188 g',
      battery_capacity: '5000 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 301 511', 'ETSI EN 301 908', 'IEC 62209-1'],
      test_laboratory: 'Bureau Veritas South Africa (Pty) Ltd',
      test_report_ref: 'BV-ZA-2026-001234',
      test_date: '2026-02-01',
      declaration: 'I hereby declare that the equipment described above complies with the relevant BOCRA type approval requirements.',
      previously_approved: false,
    },
    documents: [
      { id: 'doc-101', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'VERIFIED', file_name: 'BV_RF_Redmi13.pdf' },
      { id: 'doc-102', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'VERIFIED', file_name: 'BV_SAR_Redmi13.pdf' },
      { id: 'doc-103', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'VERIFIED', file_name: 'IEC62368_Redmi13.pdf' },
      { id: 'doc-104', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'VERIFIED', file_name: 'Redmi13_UserManual.pdf' },
      { id: 'doc-105', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'VERIFIED', file_name: 'Redmi13_Label.pdf' },
      { id: 'doc-106', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'VERIFIED', file_name: 'Redmi13_BlockDiagram.pdf' },
      { id: 'doc-107', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'VERIFIED', file_name: 'Import_Permit_Redmi13.pdf' },
      { id: 'doc-108', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'VERIFIED', file_name: 'Redmi13_Photos.zip' },
    ],
    assigned_to: { id: 'off-002', name: 'Boipelo Kgosi' },
    certificate: {
      certificate_number: 'TA/BW/2026/00094',
      issued_at: '2026-03-25T00:00:00Z',
      qr_token: 'BOCRA-TA-2026-00094-QR',
    },
    timeline: [
      { date: '2026-03-14T10:00:00Z', event: 'Application Submitted',           actor: 'Kabo Moeti (TeleCo BW)',    note: 'Complete submission.' },
      { date: '2026-03-15T08:00:00Z', event: 'Assigned to Officer',             actor: 'Admin Portal',             note: 'Assigned to Boipelo Kgosi.' },
      { date: '2026-03-17T11:00:00Z', event: 'Documents Verified',              actor: 'Boipelo Kgosi (Officer)',  note: 'All documents verified.' },
      { date: '2026-03-20T09:00:00Z', event: 'Technical Validation Passed',     actor: 'Boipelo Kgosi (Officer)',  note: 'Technical specs meet BOCRA standards.' },
      { date: '2026-03-25T14:00:00Z', event: 'Application Approved',            actor: 'Boipelo Kgosi (Officer)',  note: 'Certificate issued: TA/BW/2026/00094.' },
    ],
  },

  'TA-APP-2026-0031': {
    id: 'TA-APP-2026-0031',
    application_number: 'TA-APP-2026-0031',
    submitted_at: '2026-03-03T09:00:00Z',
    current_status_code: 'MORE_INFO',
    current_stage_code: 'DOCUMENT_VERIFICATION',
    priority_code: 'NORMAL',
    expected_decision_at: '2026-03-31T00:00:00Z',
    applicant: {
      org_name: 'TeleCo BW (Pty) Ltd',
      contact_name: 'Kabo Moeti',
      contact_email: 'kabo.moeti@teleco.co.bw',
      contact_phone: '+267 71 234 567',
      physical_address: 'Plot 54368, Gaborone CBD, Gaborone',
      accreditation_type: 'Manufacturer',
      accreditation_ref: 'ACC-2025-MFR-00041',
    },
    device: {
      brand_name: 'Huawei',
      marketing_name: 'MatePad Pro 12',
      model_name: 'WGR-W09',
      is_sim_enabled: false,
      sample_imei: 'N/A (Non-SIM device)',
      country_of_manufacture: 'China',
      frequency_bands: '2.4 GHz / 5 GHz (Wi-Fi), Bluetooth 5.1',
      transmission_power: '20 dBm (Wi-Fi)',
      network_technology: ['Wi-Fi 6', 'Bluetooth 5.1'],
      dimensions: '267.0 × 196.3 × 6.7 mm',
      weight: '609 g',
      battery_capacity: '10050 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 300 328', 'ETSI EN 301 893', 'IEC 62209-2'],
      test_laboratory: 'Intertek South Africa',
      test_report_ref: 'ITK-ZA-2026-WF-00887',
      test_date: '2026-01-22',
      declaration: 'I declare that the information provided is accurate and complete.',
      previously_approved: false,
    },
    documents: [
      { id: 'doc-201', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'REJECTED',   file_name: 'ITK_RF_MatePad.pdf',    note: 'Report does not cover 5 GHz band testing. Please resubmit.' },
      { id: 'doc-202', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'VERIFIED',   file_name: 'ITK_SAR_MatePad.pdf' },
      { id: 'doc-203', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'VERIFIED',   file_name: 'IEC62368_MatePad.pdf' },
      { id: 'doc-204', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'SUBMITTED',  file_name: 'MatePad_UserManual.pdf' },
      { id: 'doc-205', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'MISSING',    file_name: null },
      { id: 'doc-206', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'VERIFIED',   file_name: 'MatePad_BlockDiagram.pdf' },
      { id: 'doc-207', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'SUBMITTED',  file_name: 'Import_Permit_MatePad.pdf' },
      { id: 'doc-208', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'VERIFIED',   file_name: 'MatePad_Photos.zip' },
    ],
    assigned_to: { id: 'off-003', name: 'Thato Sebele' },
    timeline: [
      { date: '2026-03-03T09:00:00Z', event: 'Application Submitted',        actor: 'Kabo Moeti (TeleCo BW)',   note: null },
      { date: '2026-03-04T10:00:00Z', event: 'Assigned to Officer',          actor: 'Admin Portal',            note: 'Assigned to Thato Sebele.' },
      { date: '2026-03-07T14:00:00Z', event: 'Document Review Started',      actor: 'Thato Sebele (Officer)',  note: null },
      { date: '2026-03-10T11:30:00Z', event: 'Additional Info Requested',    actor: 'Thato Sebele (Officer)',  note: 'RF test report incomplete — missing 5 GHz band. Label artwork not submitted.' },
    ],
  },

  'TA-APP-2026-0022': {
    id: 'TA-APP-2026-0022',
    application_number: 'TA-APP-2026-0022',
    submitted_at: '2026-02-12T08:00:00Z',
    current_status_code: 'APPROVED',
    current_stage_code: 'COMPLETED',
    priority_code: 'NORMAL',
    expected_decision_at: '2026-02-26T00:00:00Z',
    applicant: {
      org_name: 'TeleCo BW (Pty) Ltd',
      contact_name: 'Kabo Moeti',
      contact_email: 'kabo.moeti@teleco.co.bw',
      contact_phone: '+267 71 234 567',
      physical_address: 'Plot 54368, Gaborone CBD, Gaborone',
      accreditation_type: 'Customer',
      accreditation_ref: 'ACC-2025-CUS-00183',
    },
    device: {
      brand_name: 'Apple',
      marketing_name: 'iPhone 16 Pro',
      model_name: 'A3293',
      is_sim_enabled: true,
      sample_imei: '354038170012345',
      country_of_manufacture: 'China',
      frequency_bands: 'B1, B3, B7, B8, B20, B28, n1, n3, n28, n77, n78, n79',
      transmission_power: '23 dBm (LTE) / 26 dBm (NR)',
      network_technology: ['5G NR', 'LTE', 'WCDMA', 'GSM'],
      dimensions: '149.6 × 71.5 × 8.25 mm',
      weight: '199 g',
      battery_capacity: '3582 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 301 511', 'ETSI EN 301 908', 'ETSI EN 303 413', 'IEC 62209-1'],
      test_laboratory: 'UL International (South Africa)',
      test_report_ref: 'UL-ZA-2026-001045',
      test_date: '2026-01-10',
      declaration: 'I declare compliance with all applicable BOCRA type approval requirements.',
      previously_approved: true,
      previous_country: 'Kenya',
      previous_reference: 'CA-KE-TA-2025-0412',
    },
    documents: [
      { id: 'doc-301', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'VERIFIED', file_name: 'UL_RF_iPhone16Pro.pdf' },
      { id: 'doc-302', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'VERIFIED', file_name: 'UL_SAR_iPhone16Pro.pdf' },
      { id: 'doc-303', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'VERIFIED', file_name: 'IEC62368_iPhone16Pro.pdf' },
      { id: 'doc-304', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'VERIFIED', file_name: 'iPhone16Pro_UserManual.pdf' },
      { id: 'doc-305', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'VERIFIED', file_name: 'iPhone16Pro_Label.pdf' },
      { id: 'doc-306', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'VERIFIED', file_name: 'iPhone16Pro_BlockDiagram.pdf' },
      { id: 'doc-307', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'VERIFIED', file_name: 'Import_Permit_iPhone16Pro.pdf' },
      { id: 'doc-308', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'VERIFIED', file_name: 'iPhone16Pro_Photos.zip' },
    ],
    assigned_to: { id: 'off-004', name: 'Naledi Moagi' },
    certificate: {
      certificate_number: 'TA/BW/2026/00067',
      issued_at: '2026-02-24T00:00:00Z',
      qr_token: 'BOCRA-TA-2026-00067-QR',
    },
    timeline: [
      { date: '2026-02-12T08:00:00Z', event: 'Application Submitted',       actor: 'Kabo Moeti (TeleCo BW)',   note: null },
      { date: '2026-02-13T09:00:00Z', event: 'Assigned to Officer',         actor: 'Admin Portal',            note: 'Assigned to Naledi Moagi.' },
      { date: '2026-02-15T11:00:00Z', event: 'Documents Verified',          actor: 'Naledi Moagi (Officer)',  note: null },
      { date: '2026-02-19T14:00:00Z', event: 'Technical Validation Passed', actor: 'Naledi Moagi (Officer)',  note: 'All specs compliant.' },
      { date: '2026-02-24T10:00:00Z', event: 'Application Approved',        actor: 'Naledi Moagi (Officer)',  note: 'Certificate issued: TA/BW/2026/00067.' },
    ],
  },

  'TA-APP-2026-0011': {
    id: 'TA-APP-2026-0011',
    application_number: 'TA-APP-2026-0011',
    submitted_at: '2026-01-05T10:00:00Z',
    current_status_code: 'REJECTED',
    current_stage_code: 'DOCUMENT_VERIFICATION',
    priority_code: 'LOW',
    expected_decision_at: '2026-01-19T00:00:00Z',
    applicant: {
      org_name: 'TeleCo BW (Pty) Ltd',
      contact_name: 'Kabo Moeti',
      contact_email: 'kabo.moeti@teleco.co.bw',
      contact_phone: '+267 71 234 567',
      physical_address: 'Plot 54368, Gaborone CBD, Gaborone',
      accreditation_type: 'Repair Provider',
      accreditation_ref: 'ACC-2025-REP-00012',
    },
    device: {
      brand_name: 'Asus',
      marketing_name: 'ZenFone 10',
      model_name: 'AI2302',
      is_sim_enabled: true,
      sample_imei: '359812110031456',
      country_of_manufacture: 'Taiwan',
      frequency_bands: 'B1, B3, B7, B8, B20, B28',
      transmission_power: '23 dBm',
      network_technology: ['LTE', 'WCDMA', 'GSM'],
      dimensions: '146.5 × 68.1 × 9.4 mm',
      weight: '172 g',
      battery_capacity: '4300 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 301 511'],
      test_laboratory: 'TÜV Rheinland South Africa',
      test_report_ref: 'TUV-ZA-2026-RF-00231',
      test_date: '2025-12-15',
      declaration: 'I declare that the information provided is accurate.',
      previously_approved: false,
    },
    documents: [
      { id: 'doc-401', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'REJECTED', file_name: 'TUV_RF_ZenFone10.pdf',  note: 'Report is expired (over 12 months old). Must not pre-date application by more than 12 months.' },
      { id: 'doc-402', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'MISSING',  file_name: null,                    note: 'SAR report not submitted.' },
      { id: 'doc-403', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'REJECTED', file_name: 'IEC62368_ZenFone10.pdf', note: 'Certificate scope does not include this specific model variant.' },
      { id: 'doc-404', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'VERIFIED', file_name: 'ZenFone10_UserManual.pdf' },
      { id: 'doc-405', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'VERIFIED', file_name: 'ZenFone10_Label.pdf' },
      { id: 'doc-406', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'VERIFIED', file_name: 'ZenFone10_BlockDiagram.pdf' },
      { id: 'doc-407', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'VERIFIED', file_name: 'Import_Permit_ZenFone10.pdf' },
      { id: 'doc-408', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'VERIFIED', file_name: 'ZenFone10_Photos.zip' },
    ],
    assigned_to: { id: 'off-005', name: 'Kefilwe Sithole' },
    timeline: [
      { date: '2026-01-05T10:00:00Z', event: 'Application Submitted',     actor: 'Kabo Moeti (TeleCo BW)',    note: null },
      { date: '2026-01-06T09:00:00Z', event: 'Assigned to Officer',       actor: 'Admin Portal',             note: 'Assigned to Kefilwe Sithole.' },
      { date: '2026-01-08T11:00:00Z', event: 'Document Review Started',   actor: 'Kefilwe Sithole (Officer)', note: null },
      { date: '2026-01-12T14:30:00Z', event: 'Application Rejected',      actor: 'Kefilwe Sithole (Officer)', note: 'RF test report expired. SAR report missing. Safety certificate scope mismatch. Applicant may re-apply with updated documentation.' },
    ],
  },

  'TA-APP-2026-0098': {
    id: 'TA-APP-2026-0098',
    application_number: 'TA-APP-2026-0098',
    submitted_at: '2026-03-20T11:00:00Z',
    current_status_code: 'PENDING',
    current_stage_code: 'INITIAL_REVIEW',
    priority_code: 'NORMAL',
    expected_decision_at: '2026-04-10T00:00:00Z',
    applicant: {
      org_name: 'TeleCo BW (Pty) Ltd',
      contact_name: 'Lesedi Gabanne',
      contact_email: 'l.gabanne@teleco.co.bw',
      contact_phone: '+267 71 456 789',
      physical_address: 'Plot 54368, Gaborone CBD, Gaborone',
      accreditation_type: 'Customer',
      accreditation_ref: 'ACC-2025-CUS-00183',
    },
    device: {
      brand_name: 'Xiaomi',
      marketing_name: 'Redmi 14C',
      model_name: '24117RKAEG',
      is_sim_enabled: true,
      sample_imei: '868753070012345',
      country_of_manufacture: 'China',
      frequency_bands: 'B1, B3, B7, B8, B20, B28',
      transmission_power: '23 dBm',
      network_technology: ['LTE', 'WCDMA', 'GSM'],
      dimensions: '168.5 × 76.3 × 8.2 mm',
      weight: '211 g',
      battery_capacity: '5160 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 301 511', 'ETSI EN 301 908'],
      test_laboratory: 'SGS Botswana Testing Laboratory',
      test_report_ref: 'SGS-BW-2026-RF-00398',
      test_date: '2026-03-01',
      declaration: 'I declare compliance with all applicable BOCRA type approval requirements.',
      previously_approved: false,
    },
    documents: [
      { id: 'doc-501', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'SUBMITTED', file_name: 'SGS_RF_Redmi14C.pdf' },
      { id: 'doc-502', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'SUBMITTED', file_name: 'SGS_SAR_Redmi14C.pdf' },
      { id: 'doc-503', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'SUBMITTED', file_name: 'IEC62368_Redmi14C.pdf' },
      { id: 'doc-504', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'SUBMITTED', file_name: 'Redmi14C_Manual.pdf' },
      { id: 'doc-505', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'SUBMITTED', file_name: 'Redmi14C_Label.pdf' },
      { id: 'doc-506', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'SUBMITTED', file_name: 'Redmi14C_Diagram.pdf' },
      { id: 'doc-507', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'SUBMITTED', file_name: 'Import_Redmi14C.pdf' },
      { id: 'doc-508', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'SUBMITTED', file_name: 'Redmi14C_Photos.zip' },
    ],
    assigned_to: null,
    timeline: [
      { date: '2026-03-20T11:00:00Z', event: 'Application Submitted', actor: 'Lesedi Gabanne (TeleCo BW)', note: 'Pending initial assignment.' },
    ],
  },

  'TA-APP-2026-0097': {
    id: 'TA-APP-2026-0097',
    application_number: 'TA-APP-2026-0097',
    submitted_at: '2026-03-19T09:30:00Z',
    current_status_code: 'UNDER_REVIEW',
    current_stage_code: 'DOCUMENT_VERIFICATION',
    priority_code: 'NORMAL',
    expected_decision_at: '2026-04-08T00:00:00Z',
    applicant: {
      org_name: 'Linkserve Botswana',
      contact_name: 'Mpho Segaetsho',
      contact_email: 'm.segaetsho@linkserve.co.bw',
      contact_phone: '+267 74 321 654',
      physical_address: 'Plot 14462, Fairgrounds, Gaborone',
      accreditation_type: 'Manufacturer',
      accreditation_ref: 'ACC-2025-MFR-00039',
    },
    device: {
      brand_name: 'Samsung',
      marketing_name: 'Galaxy Tab S9',
      model_name: 'SM-X710',
      is_sim_enabled: false,
      sample_imei: 'N/A (Wi-Fi only)',
      country_of_manufacture: 'Vietnam',
      frequency_bands: '2.4 GHz / 5 GHz (Wi-Fi 6E), Bluetooth 5.3',
      transmission_power: '20 dBm (Wi-Fi)',
      network_technology: ['Wi-Fi 6E', 'Bluetooth 5.3'],
      dimensions: '254.0 × 165.8 × 5.9 mm',
      weight: '498 g',
      battery_capacity: '8400 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 300 328', 'ETSI EN 301 893', 'IEC 62209-2'],
      test_laboratory: 'SGS Botswana Testing Laboratory',
      test_report_ref: 'SGS-BW-2026-WF-00401',
      test_date: '2026-02-20',
      declaration: 'I declare that all information is accurate and complete.',
      previously_approved: false,
    },
    documents: [
      { id: 'doc-601', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'SUBMITTED', file_name: 'SGS_RF_TabS9.pdf' },
      { id: 'doc-602', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'SUBMITTED', file_name: 'SGS_SAR_TabS9.pdf' },
      { id: 'doc-603', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'SUBMITTED', file_name: 'IEC62368_TabS9.pdf' },
      { id: 'doc-604', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'SUBMITTED', file_name: 'TabS9_Manual.pdf' },
      { id: 'doc-605', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'SUBMITTED', file_name: 'TabS9_Label.pdf' },
      { id: 'doc-606', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'SUBMITTED', file_name: 'TabS9_Diagram.pdf' },
      { id: 'doc-607', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'SUBMITTED', file_name: 'Import_TabS9.pdf' },
      { id: 'doc-608', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'SUBMITTED', file_name: 'TabS9_Photos.zip' },
    ],
    assigned_to: null,
    timeline: [
      { date: '2026-03-19T09:30:00Z', event: 'Application Submitted',  actor: 'Mpho Segaetsho (Linkserve)', note: null },
      { date: '2026-03-20T08:00:00Z', event: 'Initial Review Started', actor: 'System',                    note: 'Entered document verification queue.' },
    ],
  },

  'TA-APP-2026-0094': {
    id: 'TA-APP-2026-0094',
    application_number: 'TA-APP-2026-0094',
    submitted_at: '2026-03-12T14:00:00Z',
    current_status_code: 'UNDER_REVIEW',
    current_stage_code: 'TECHNICAL_VALIDATION',
    priority_code: 'HIGH',
    expected_decision_at: '2026-03-31T00:00:00Z',
    applicant: {
      org_name: 'BotswanaTel Communications',
      contact_name: 'Onthatile Molefe',
      contact_email: 'o.molefe@botswanatel.co.bw',
      contact_phone: '+267 75 987 123',
      physical_address: 'Plot 9876, Main Mall, Gaborone',
      accreditation_type: 'Customer',
      accreditation_ref: 'ACC-2025-CUS-00201',
    },
    device: {
      brand_name: 'Apple',
      marketing_name: 'iPad Air M2',
      model_name: 'MUWJ3LL/A',
      is_sim_enabled: false,
      sample_imei: 'N/A (Wi-Fi only)',
      country_of_manufacture: 'China',
      frequency_bands: '2.4 GHz / 5 GHz / 6 GHz (Wi-Fi 6E), Bluetooth 5.3',
      transmission_power: '20 dBm (Wi-Fi)',
      network_technology: ['Wi-Fi 6E', 'Bluetooth 5.3'],
      dimensions: '247.6 × 178.5 × 6.1 mm',
      weight: '462 g',
      battery_capacity: '7606 mAh',
    },
    standards: {
      compliance: ['IEC 62368-1', 'ETSI EN 300 328', 'ETSI EN 301 893', 'ETSI EN 303 413'],
      test_laboratory: 'UL International (South Africa)',
      test_report_ref: 'UL-ZA-2026-001102',
      test_date: '2026-02-28',
      declaration: 'I declare compliance with all applicable BOCRA type approval requirements.',
      previously_approved: true,
      previous_country: 'South Africa',
      previous_reference: 'ICASA-TA-2025-0119',
    },
    documents: [
      { id: 'doc-701', type_code: 'TEST_REPORT',   label: 'RF Test Report',                status: 'VERIFIED',  file_name: 'UL_RF_iPadAirM2.pdf' },
      { id: 'doc-702', type_code: 'SAR_REPORT',    label: 'SAR / EMF Report',              status: 'VERIFIED',  file_name: 'UL_SAR_iPadAirM2.pdf' },
      { id: 'doc-703', type_code: 'SAFETY_CERT',   label: 'Electrical Safety Certificate', status: 'VERIFIED',  file_name: 'IEC62368_iPadAirM2.pdf' },
      { id: 'doc-704', type_code: 'USER_MANUAL',   label: 'User Manual (English)',         status: 'VERIFIED',  file_name: 'iPadAirM2_Manual.pdf' },
      { id: 'doc-705', type_code: 'LABEL_ARTWORK', label: 'Device Label / Artwork',        status: 'SUBMITTED', file_name: 'iPadAirM2_Label.pdf' },
      { id: 'doc-706', type_code: 'BLOCK_DIAGRAM', label: 'Block / Circuit Diagram',       status: 'VERIFIED',  file_name: 'iPadAirM2_Diagram.pdf' },
      { id: 'doc-707', type_code: 'IMPORT_PERMIT', label: 'Import Permit',                 status: 'VERIFIED',  file_name: 'Import_iPadAirM2.pdf' },
      { id: 'doc-708', type_code: 'DEVICE_PHOTOS', label: 'Device Photographs',            status: 'VERIFIED',  file_name: 'iPadAirM2_Photos.zip' },
    ],
    assigned_to: null,
    timeline: [
      { date: '2026-03-12T14:00:00Z', event: 'Application Submitted',           actor: 'Onthatile Molefe (BotswanaTel)', note: null },
      { date: '2026-03-13T09:00:00Z', event: 'Assigned to Officer',             actor: 'Admin Portal',                  note: 'Marked HIGH priority due to deadline.' },
      { date: '2026-03-16T11:00:00Z', event: 'Documents Verified',              actor: 'System',                        note: null },
      { date: '2026-03-19T09:00:00Z', event: 'Advanced to Technical Validation', actor: 'System',                       note: null },
    ],
  },
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params
  const application = MOCK_APPLICATIONS[id]

  if (!application) {
    return NextResponse.json({ error: 'Application not found' }, { status: 404 })
  }

  return NextResponse.json(application)
}
